"""add useraddress table

Revision ID: 3b3eb28823fa
Revises: f5ad7e3a6b6a
Create Date: 2023-12-01 05:11:32.221560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b3eb28823fa'
down_revision = 'f5ad7e3a6b6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('useraddresstable',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, cache=1), nullable=False),
    sa.Column('order_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['ordertable.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('paymenttable')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymenttable',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('payment_type', postgresql.ENUM('cache', 'card', name='paymenttype'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['ordertable.id'], name='paymenttable_order_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='paymenttable_pkey')
    )
    op.drop_table('useraddresstable')
    # ### end Alembic commands ###
    sa.Enum(name="language").drop(op.get_bind())
    sa.Enum(name="member").drop(op.get_bind())
    sa.Enum(name="productmode").drop(op.get_bind())
    sa.Enum(name="menuproductstatus").drop(op.get_bind())
    sa.Enum(name="productstatus").drop(op.get_bind())
    sa.Enum(name="paymenttype").drop(op.get_bind())
    sa.Enum(name="orderstatus").drop(op.get_bind())
    sa.Enum(name="ordertype").drop(op.get_bind())
    sa.Enum(name="basketstatus").drop(op.get_bind())
    sa.Enum(name="telegramstatus").drop(op.get_bind())