"""two

Revision ID: 759802c237d5
Revises: 152e96024f44
Create Date: 2023-09-29 20:04:32.527440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759802c237d5'
down_revision = '152e96024f44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurantbannertable',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, cache=1), nullable=False),
    sa.Column('restaurant_id', sa.BIGINT(), nullable=False),
    sa.Column('banner_url', sa.VARCHAR(length=500), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restauranttable.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurantbannertable')
    # ### end Alembic commands ###
