"""fix size columns

Revision ID: ce19b1cb1464
Revises: 759802c237d5
Create Date: 2023-11-01 17:56:28.977204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce19b1cb1464'
down_revision = '759802c237d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categorynametable', 'category',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('productdescriptiontable', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('productimagetable', 'image',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('productnametable', 'name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('productpricenametable', 'name',
               existing_type=sa.VARCHAR(length=55),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('restaurantlocationstable', 'address',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('restaurantnamedescriptiontable', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('restaurantnamedescriptiontable', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('shippingordertable', 'address',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('shippingordertable', 'comment',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shippingordertable', 'comment',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('shippingordertable', 'address',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('restaurantnamedescriptiontable', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('restaurantnamedescriptiontable', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('restaurantlocationstable', 'address',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('productpricenametable', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=55),
               existing_nullable=False)
    op.alter_column('productnametable', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('productimagetable', 'image',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('productdescriptiontable', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('categorynametable', 'category',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
