version: "3.5"

services:
  db:
    image: postgres:14.9
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=525643916096
    ports:
      - "5435:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    container_name: restaurant-back
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_volume:

networks:
  app-network:
    driver: bridge
