version: "3.5"

services:
  db:
    image: postgres:14.9
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=525643916096
    ports:
      - "5435:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - app-network

  cache:
    image: redis:7.2
    container_name: cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network
    command: redis-server --requirepass gDI1KaUqnbzbqRxEtxTY0vXRQ/yR6rTFnRBr2putcU0d++uiX8vLw5++zfEXybjSJh73kNS8xOPaZlA1
    volumes:
      - cache:/data

  app:
    container_name: restaurant-back
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
    networks:
      - app-network

volumes:
  db_volume:
  cache:
    driver: local

networks:
  app-network:
    driver: bridge
